services:

  frontend:
    image: node:18
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'

  backend:
    build: ./backend
    init: true
    volumes:
      - ./backend:/app
    ports:
      - 8081:8081
    environment:
      LOG_LEVEL: DEBUG
    command: adev runserver --port 8081 .

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  postgres:
  redis: