services:

  frontend:
    image: node:18
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c 'npm install && npm run dev'

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - redis:/data

volumes:
  postgres:
  redis: